2025-06-15 01:32:38,607 - INFO - Starting training for RandomForestModel on filtered_features.csv
2025-06-15 01:32:38,667 - INFO - Loaded dataset with 7515 samples and 52 features
2025-06-15 01:32:38,678 - INFO - Split data into 635 training files and 159 test files
2025-06-15 01:32:38,678 - ERROR - Error during model training: 'RandomForestModel' object has no attribute 'get_optuna_params'
2025-06-15 01:35:51,414 - INFO - Starting training for RandomForestModel on filtered_features.csv
2025-06-15 01:35:51,464 - INFO - Loaded dataset with 7515 samples and 52 features
2025-06-15 01:35:51,470 - INFO - Split data into 635 training files and 159 test files
2025-06-15 01:48:28,166 - INFO - Starting training for SVCModel on filtered_features.csv
2025-06-15 01:48:28,223 - INFO - Loaded dataset with 7515 samples and 52 features
2025-06-15 01:48:28,233 - INFO - Split data into 635 training files and 159 test files
2025-06-15 01:49:34,897 - INFO - Training completed for SVCModel
2025-06-15 01:49:34,897 - INFO - Best parameters: {'C': 0.7261696974503035, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None}
2025-06-15 01:49:34,897 - INFO - Test metrics: {'accuracy': 0.7905723905723906, 'f1_score': 0.7883787339388925, 'precision': 0.7940663965700859, 'recall': 0.7905723905723906, 'confusion_matrix': array([[125,  46,  46],
       [  7, 388,  91],
       [ 19, 102, 661]])}
2025-06-15 01:49:34,897 - INFO - Model saved to: models/saved\SVCModel_filtered_features.joblib
2025-06-15 01:49:34,897 - INFO - Results saved to: results\SVCModel_filtered_features_results.joblib
2025-06-15 01:49:53,913 - INFO - Starting training for XGBoostModel on filtered_features.csv
2025-06-15 01:49:53,966 - INFO - Loaded dataset with 7515 samples and 52 features
2025-06-15 01:49:53,972 - INFO - Split data into 635 training files and 159 test files
2025-06-15 01:49:59,789 - ERROR - Error during model training: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Eve\Documents\PK\II_Stopien\Zajecia\Semestr_2\Zaawansowane_metody_uczenia_maszynowego\Projekt2\birds-classification\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Eve\Documents\PK\II_Stopien\Zajecia\Semestr_2\Zaawansowane_metody_uczenia_maszynowego\Projekt2\birds-classification\.venv\Lib\site-packages\xgboost\core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\Users\Eve\Documents\PK\II_Stopien\Zajecia\Semestr_2\Zaawansowane_metody_uczenia_maszynowego\Projekt2\birds-classification\.venv\Lib\site-packages\xgboost\sklearn.py", line 1640, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['calqua' 'comwax' 'houfin']

2025-06-15 01:51:56,031 - INFO - Starting training for XGBoostModel on filtered_features.csv
2025-06-15 01:51:56,081 - INFO - Loaded dataset with 7515 samples and 52 features
2025-06-15 01:51:56,098 - INFO - Split data into 635 training files and 159 test files
2025-06-15 01:52:58,124 - ERROR - Error during model training: multi_class must be in ('ovo', 'ovr')
